-- Ejecuta este archivo una sola vez en Supabase: SQL Editor > New query > Run.
-- Guarda los destinos para que aparezcan igual en todos los móviles.
create table if not exists public.destinations (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  subtitle text not null,
  created_at timestamptz not null default now()
);

alter table public.destinations enable row level security;

create policy "Cualquiera puede ver destinos"
on public.destinations for select
to anon, authenticated
using (true);

create policy "Usuarios identificados crean destinos"
on public.destinations for insert
to authenticated
with check (true);

insert into public.destinations (slug, name, subtitle)
values
  ('oporto-portugal', 'Oporto, Portugal', 'Azulejos, vino y calles que invitan a perderse.'),
  ('galicia', 'Galicia', 'Océano, lluvia suave y sobremesas eternas.')
on conflict (slug) do nothing;

-- La galería pública necesita poder consultar los nombres de los archivos.
-- Tus fotos siguen protegidas frente a subidas o borrados anónimos.
create policy "Cualquiera puede listar las fotos públicas"
on storage.objects for select
to anon
using (bucket_id = 'viajes');
